### ISSUE TITLE
Unable to compile on CentOS 7.6

### ISSUE THREAD

**Issue by MatheMatrix** [bytedance/trace-irqoff#1]
## Environment

```bash
[root@mini-007318b trace-irqoff]# rpm -qa | grep -E 'kernel|gcc'
kernel-3.10.0-957.10.1.el7.x86_64
gcc-4.8.5-39.el7.x86_64
mlnx-ofa_kernel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
kernel-headers-3.10.0-957.10.1.el7.x86_64
kmod-kernel-mft-mlnx-4.12.0-1.rhel7u6.x86_64
gcc-gfortran-4.8.5-39.el7.x86_64
mlnx-ofa_kernel-devel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
kernel-devel-3.10.0-957.10.1.el7.x86_64
kmod-mlnx-ofa_kernel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
kernel-tools-libs-3.10.0-957.10.1.el7.x86_64
kernel-tools-3.10.0-957.10.1.el7.x86_64
libgcc-4.8.5-39.el7.x86_64
```

```bash
[root@mini-007318b trace-irqoff]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

## Problem

```bash
[root@mini-007318b trace-irqoff]# make -j 8
make -C /lib/modules/3.10.0-957.10.1.el7.x86_64/build M=/root/trace-irqoff modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
  CC [M]  /root/trace-irqoff/trace_irqoff.o
/root/trace-irqoff/trace_irqoff.c:584:12: error: static declaration of 'kstrtobool_from_user' follows non-static declaration
 static int kstrtobool_from_user(const char __user *s, size_t count, bool *res)
            ^
In file included from include/linux/rbtree.h:32:0,
                 from include/linux/hrtimer.h:18,
                 from /root/trace-irqoff/trace_irqoff.c:13:
include/linux/kernel.h:376:18: note: previous declaration of 'kstrtobool_from_user' was here
 int __must_check kstrtobool_from_user(const char __user *s, size_t count, bool *res);
                  ^
make[2]: *** [/root/trace-irqoff/trace_irqoff.o] Error 1
make[1]: *** [_module_/root/trace-irqoff] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
make: *** [all] Error 2
```

**Comment by MatheMatrix** [comment]
This could be solved by:

```bash
[root@-mini-007318b trace-irqoff]# make
make -C /lib/modules/3.10.0-957.10.1.el7.x86_64/build M=/root/trace-irqoff modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
  CC [M]  /root/trace-irqoff/trace_irqoff.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/trace-irqoff/trace_irqoff.mod.o
  LD [M]  /root/trace-irqoff/trace_irqoff.ko
make[1]: Leaving directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
[root@-mini-007318b trace-irqoff]#
[root@-mini-007318b trace-irqoff]#
[root@-mini-007318b trace-irqoff]# git diff
diff --git a/trace_irqoff.c b/trace_irqoff.c
index 4b2834c..02eb21f 100644
--- a/trace_irqoff.c
+++ b/trace_irqoff.c
@@ -581,17 +581,17 @@ static void trace_irqoff_cancel_timers(void)
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4, 4, 0)
 #include <linux/string.h>

-static int kstrtobool_from_user(const char __user *s, size_t count, bool *res)
-{
-       /* Longest string needed to differentiate, newline, terminator */
-       char buf[4];
-
-       count = min(count, sizeof(buf) - 1);
-       if (copy_from_user(buf, s, count))
-               return -EFAULT;
-       buf[count] = '\0';
-       return strtobool(buf, res);
-}
+//static int kstrtobool_from_user(const char __user *s, size_t count, bool *res)
+//{
+//     /* Longest string needed to differentiate, newline, terminator */
+//     char buf[4];
+//
+//     count = min(count, sizeof(buf) - 1);
+//     if (copy_from_user(buf, s, count))
+//             return -EFAULT;
+//     buf[count] = '\0';
+//     return strtobool(buf, res);
+//}
 #endif

 static ssize_t enable_write(struct file *file, const char __user *buf,
[root@-mini-007318b trace-irqoff]#
```

**Comment by smcdef** [comment]
> This could be solved by:
> 
> ```diff
> [root@mini-007318b trace-irqoff]# git diff
> diff --git a/trace_irqoff.c b/trace_irqoff.c
> index 4b2834c..02eb21f 100644
> --- a/trace_irqoff.c
> +++ b/trace_irqoff.c
> @@ -581,17 +581,17 @@ static void trace_irqoff_cancel_timers(void)
>  #if LINUX_VERSION_CODE < KERNEL_VERSION(4, 4, 0)
>  #include <linux/string.h>
> 
> -static int kstrtobool_from_user(const char __user *s, size_t count, bool *res)
> -{
> -       /* Longest string needed to differentiate, newline, terminator */
> -       char buf[4];
> -
> -       count = min(count, sizeof(buf) - 1);
> -       if (copy_from_user(buf, s, count))
> -               return -EFAULT;
> -       buf[count] = '\0';
> -       return strtobool(buf, res);
> -}
> +//static int kstrtobool_from_user(const char __user *s, size_t count, bool *res)
> +//{
> +//     /* Longest string needed to differentiate, newline, terminator */
> +//     char buf[4];
> +//
> +//     count = min(count, sizeof(buf) - 1);
> +//     if (copy_from_user(buf, s, count))
> +//             return -EFAULT;
> +//     buf[count] = '\0';
> +//     return strtobool(buf, res);
> +//}
>  #endif
> 
>  static ssize_t enable_write(struct file *file, const char __user *buf,
> [root@mini-007318b trace-irqoff]#
> ```
> 
> ```shell
> [root@mini-007318b trace-irqoff]# make
> make -C /lib/modules/3.10.0-957.10.1.el7.x86_64/build M=/root/trace-irqoff modules
> make[1]: Entering directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
>   CC [M]  /root/trace-irqoff/trace_irqoff.o
>   Building modules, stage 2.
>   MODPOST 1 modules
>   CC      /root/trace-irqoff/trace_irqoff.mod.o
>   LD [M]  /root/trace-irqoff/trace_irqoff.ko
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
> [root@mini-007318b trace-irqoff]#
> ```
> 
> It is obvious that it is only temporary solution

Thanks for your solution. I will fix it later.

**Comment by smcdef** [comment]
> ## Environment
> ```shell
> [root@mini-007318b trace-irqoff]# rpm -qa | grep -E 'kernel|gcc'
> kernel-3.10.0-957.10.1.el7.x86_64
> gcc-4.8.5-39.el7.x86_64
> mlnx-ofa_kernel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
> kernel-headers-3.10.0-957.10.1.el7.x86_64
> kmod-kernel-mft-mlnx-4.12.0-1.rhel7u6.x86_64
> gcc-gfortran-4.8.5-39.el7.x86_64
> mlnx-ofa_kernel-devel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
> kernel-devel-3.10.0-957.10.1.el7.x86_64
> kmod-mlnx-ofa_kernel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
> kernel-tools-libs-3.10.0-957.10.1.el7.x86_64
> kernel-tools-3.10.0-957.10.1.el7.x86_64
> libgcc-4.8.5-39.el7.x86_64
> ```
> 
> ```shell
> [root@mini-007318b trace-irqoff]# cat /etc/redhat-release
> CentOS Linux release 7.6.1810 (Core)
> ```
> 
> ## Problem
> ```shell
> [root@mini-007318b trace-irqoff]# make -j 8
> make -C /lib/modules/3.10.0-957.10.1.el7.x86_64/build M=/root/trace-irqoff modules
> make[1]: Entering directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
>   CC [M]  /root/trace-irqoff/trace_irqoff.o
> /root/trace-irqoff/trace_irqoff.c:584:12: error: static declaration of 'kstrtobool_from_user' follows non-static declaration
>  static int kstrtobool_from_user(const char __user *s, size_t count, bool *res)
>             ^
> In file included from include/linux/rbtree.h:32:0,
>                  from include/linux/hrtimer.h:18,
>                  from /root/trace-irqoff/trace_irqoff.c:13:
> include/linux/kernel.h:376:18: note: previous declaration of 'kstrtobool_from_user' was here
>  int __must_check kstrtobool_from_user(const char __user *s, size_t count, bool *res);
>                   ^
> make[2]: *** [/root/trace-irqoff/trace_irqoff.o] Error 1
> make[1]: *** [_module_/root/trace-irqoff] Error 2
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
> make: *** [all] Error 2
> ```

The [kstrtobool_from_user](https://github.com/torvalds/linux/commit/ef951599074ba4fad2d0efa0a977129b41e6d203) was introduced after linux-4.6 kernel. But the kernel version you are using is linux-3.10, so in theory, the kstrtobool_from_user should not exist. Do you backport this patch to your kernel?

**Comment by MatheMatrix** [comment]
> > ## Environment
> > ```shell
> > [root@mini-007318b trace-irqoff]# rpm -qa | grep -E 'kernel|gcc'
> > kernel-3.10.0-957.10.1.el7.x86_64
> > gcc-4.8.5-39.el7.x86_64
> > mlnx-ofa_kernel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
> > kernel-headers-3.10.0-957.10.1.el7.x86_64
> > kmod-kernel-mft-mlnx-4.12.0-1.rhel7u6.x86_64
> > gcc-gfortran-4.8.5-39.el7.x86_64
> > mlnx-ofa_kernel-devel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
> > kernel-devel-3.10.0-957.10.1.el7.x86_64
> > kmod-mlnx-ofa_kernel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.rhel7u6.x86_64
> > kernel-tools-libs-3.10.0-957.10.1.el7.x86_64
> > kernel-tools-3.10.0-957.10.1.el7.x86_64
> > libgcc-4.8.5-39.el7.x86_64
> > ```
> > 
> > 
> > ```shell
> > [root@mini-007318b trace-irqoff]# cat /etc/redhat-release
> > CentOS Linux release 7.6.1810 (Core)
> > ```
> > 
> > 
> > ## Problem
> > ```shell
> > [root@mini-007318b trace-irqoff]# make -j 8
> > make -C /lib/modules/3.10.0-957.10.1.el7.x86_64/build M=/root/trace-irqoff modules
> > make[1]: Entering directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
> >   CC [M]  /root/trace-irqoff/trace_irqoff.o
> > /root/trace-irqoff/trace_irqoff.c:584:12: error: static declaration of 'kstrtobool_from_user' follows non-static declaration
> >  static int kstrtobool_from_user(const char __user *s, size_t count, bool *res)
> >             ^
> > In file included from include/linux/rbtree.h:32:0,
> >                  from include/linux/hrtimer.h:18,
> >                  from /root/trace-irqoff/trace_irqoff.c:13:
> > include/linux/kernel.h:376:18: note: previous declaration of 'kstrtobool_from_user' was here
> >  int __must_check kstrtobool_from_user(const char __user *s, size_t count, bool *res);
> >                   ^
> > make[2]: *** [/root/trace-irqoff/trace_irqoff.o] Error 1
> > make[1]: *** [_module_/root/trace-irqoff] Error 2
> > make[1]: Leaving directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
> > make: *** [all] Error 2
> > ```
> 
> The [kstrtobool_from_user](https://github.com/torvalds/linux/commit/ef951599074ba4fad2d0efa0a977129b41e6d203) was introduced after linux-4.6 kernel. But the kernel version you are using is linux-3.10, so in theory, the kstrtobool_from_user should not exist. Do you backport this patch to your kernel?

This kernel is from CentOS 7.6, it may backported by Redhat.
